# Generated by Django 2.1 on 2019-06-26 14:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='frends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frend', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_d', models.TextField(max_length=300)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('tag', models.ForeignKey(null=True, on_delete='CASCADE', to='smwapp.frends')),
                ('user', models.OneToOneField(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('dob', models.DateField(null=True)),
                ('phoneno', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'm'), ('female', 'f')], max_length=50)),
                ('relation', models.CharField(choices=[('Singale', 's'), ('Married', 'M')], max_length=50)),
                ('user', models.OneToOneField(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
