# Generated by Django 2.1 on 2019-05-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smwapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='Aid',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
