# Generated by Django 2.1 on 2019-06-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smwapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='relation',
            field=models.CharField(choices=[('s', 'Singale'), ('M', 'Marrid')], max_length=50),
        ),
    ]
