# Generated by Django 2.1 on 2019-06-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smwapp', '0002_auto_20190626_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frends',
            name='frend',
            field=models.ForeignKey(max_length=50, on_delete='CASCADE', to='smwapp.profile'),
        ),
    ]
