# Generated by Django 2.1 on 2019-05-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smwapp', '0002_auto_20190511_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('pid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80)),
                ('post', models.TextField(max_length=200)),
                ('cdate', models.DateField(auto_now_add=True)),
                ('Author', models.ForeignKey(on_delete='CASCADE', to='smwapp.Author')),
            ],
        ),
    ]
