# Generated by Django 2.1 on 2019-06-27 08:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smwapp', '0004_auto_20190627_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frends',
            name='profile',
        ),
        migrations.AddField(
            model_name='frends',
            name='profile',
            field=models.ManyToManyField(max_length=50, to='smwapp.profile'),
        ),
        migrations.RemoveField(
            model_name='frends',
            name='user',
        ),
        migrations.AddField(
            model_name='frends',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
